language: elixir
services:
  - postgresql
elixir:
  - 1.3.4
otp_release:
  - 19.1
before_install:
  - cp config/test.secret.exs{.example,}
before_script:
  - mix do ecto.create, ecto.migrate
after_script:
  - mix coveralls.travis
env:
  - MIX_ENV=test
addons:
  postgresql: "9.4"
