language: elixir
addons:
  postgresql: '9.5'
elixir:
  - 1.3.4
otp_release:
  - 19.1
before_script:
  - mix do ecto.create, ecto.migrate
env:
  - MIX_ENV=test DATABASE_URL="postgres://travis@localhost:5432/travis"
